users:
  userId: String #uid
  email: String
  name: String #Default = unknown
  imageUrl: String?

  tokens: #documentのIDとToken統一
    token: String

  matchIds: #docmentIdとmatchId統一
    matchId: String

  rehearsalIds:
    rehearsalId: String

matches:
rehearsals:
  gameId: String
  gameTitle: String
  heldAt: Timestamp
  editorKey: String #6文字以上
  readerKey: String #6文字以上
  editorIds: [String]  #editorのuserIdリスト
  readerIds: [String] #readerのuserIdリスト

  teams:
    teamId: String
    teamName: String
    isTeam: bool
    teamTotal: num? #チームだったら

    players:
      playerId: String
      name: String
      grade: int #学年

      fx:
        scoreId: String #playerIdと一緒
        d: num
        e: num
        nd: num
        total: num
      ph:
      sr:
      vt:
      pb:
      hb:



