users:
  name: String #Default = unknown
  imageUrl: String?

  invisibleUserFields:
    email: String
    userId: String

  tokens: #documentのIDとToken統一
    token: String

  gameIds: #docmentIdとmatchId統一
    gameId: String

games:
  gameId: String
  gameTitle: String
  heldAt: Timestamp
  isRehearsal: bool
  editorKey: String #6文字以上
  readerKey: String #6文字以上
  editors: [String]  #editorのuserIdリスト
  readers: [String] #readerのuserIdリスト

  teams:
    teamId: String
    teamName: String
    isTeam: bool
    teamTotal: num #チームだったら

    players:
      playerId: String
      name: String
      grade: int #学年

      fx:
        scoreId: String #playerIdと一緒
        d: num
        e: num
        nd: num
        total: num
      ph:
      sr:
      vt:
      pb:
      hb:



