users:
  name: String
  imageUrl: String?
  userId: String

  tokens: #documentのIDとToken統一
    token: String

  gameIds: #docmentIdとmatchId統一
    gameId: String

games:
  gameId: String
  gameTitle: String
  heldAt: Timestamp
  isRehearsal: bool
  readerKey: String #6文字以上自動生成（編集可）
  editorKey: String #6文字以上
  editorIds: [String]
  readerIds: [String]
  partyIds: [String]

  parties:
    partyId: String
    partyName: String
    isTeam: bool
    teamTotal: num
    menberIds: <String>[]


    players:
      playerId: String
      name: String
      grade: int #学年
      totalScore: num
      fx: num
      ph: num
      sr: num
      vt: num
      pb: num
      hb: num

      fxDetail: #score_detail型
        scoreId: String #playerIdと一致
        d: num
        e: num
        nd: num
      phDtail:
        scoreId: String #playerIdと一致
          d: num
          e: num
          nd: num
      srDtail:
        scoreId: String #playerIdと一致
          d: num
          e: num
          nd: num
      vtDtail:
        scoreId: String #playerIdと一致
          d: num
          e: num
          nd: num
      pbDtail:
        scoreId: String #playerIdと一致
          d: num
          e: num
          nd: num
      hbDtail:
        scoreId: String #playerIdと一致
          d: num
          e: num
          nd: num

